services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mydb:/var/lib/mysql

  myapp:
    build: .
    ports:
      - "3004:3000"
    depends_on:
      - mysql
    environment: 
      - DB_HOST=mysql
      - DB_PORT=3306

volumes:
  mydb: