
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-second
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD : true
      MYSQL_DATABASE: "todo_db"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: